spring:
  application:
    name: java-security
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
    open-in-view: false
